// (c) 2026 FRINKnet & Friends - MIT Licence
//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func main() {
	out, err := os.Create("x_config.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen.go; DO NOT EDIT.")
	fmt.Fprintln(out, "package libvariance")
	fmt.Fprintln(out)

	// Generate constants from configure.x string-valued #defines.
	genConstants(out, "../x/configure.x")

	// Generate the FileType slice from filetypes.x.
	genFileTypes(out, "../x/filetypes.x")

	// Generate the Config map from configure.x.
	genConfigs(out, "../x/configure.x")

	// loadXConfig returns pre-built data — no runtime file parsing.
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func loadXConfig() ([]FileType, map[string]Config, error) {")
	fmt.Fprintln(out, "\treturn _fileTypes, _configs, nil")
	fmt.Fprintln(out, "}")
}

// ─── FileType generation ───────────────────────────────────────────────

func genFileTypes(out *os.File, path string) {
	f, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	var entries []string
	lineNo := 0

	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		args := splitXArgs(line)
		if len(args) != 3 {
			panic(fmt.Sprintf("%s:%d: expected X(lang, exts, mark), got %q", path, lineNo, line))
		}
		lang := cleanXName(args[0])
		exts := trimXValue(args[1])
		mark := trimXValue(args[2])
		if lang == "" || exts == "" || mark == "" {
			panic(fmt.Sprintf("%s:%d: empty X fields", path, lineNo))
		}
		entries = append(entries, fmt.Sprintf("\t{ Lang: %q, Ext: %q, Mark: %q },", lang, exts, mark))
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}

	fmt.Fprintf(out, "\n// fileTypes is pre-built from %s.\n", path)
	fmt.Fprintln(out, "var _fileTypes = []FileType{")
	for _, e := range entries {
		fmt.Fprintln(out, e)
	}
	fmt.Fprintln(out, "}")
}

func splitXArgs(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "X(")
	line = strings.TrimSuffix(line, ")")
	var out []string
	var b strings.Builder
	inQuotes := false
	inBraces := false
	for _, r := range line {
		switch r {
		case '"':
			inQuotes = !inQuotes
			b.WriteRune(r)
		case '{':
			inBraces = true
			b.WriteRune(r)
		case '}':
			inBraces = false
			b.WriteRune(r)
		case ',':
			if !inQuotes && !inBraces {
				out = append(out, strings.TrimSpace(b.String()))
				b.Reset()
				continue
			}
			b.WriteRune(r)
		default:
			b.WriteRune(r)
		}
	}
	out = append(out, strings.TrimSpace(b.String()))
	return out
}

func trimXValue(value string) string {
	value = strings.TrimSpace(value)
	value = strings.TrimSuffix(value, ")")
	value = strings.Trim(value, "\"")
	return strings.TrimSpace(value)
}

func cleanXName(value string) string {
	value = strings.TrimSpace(value)
	value = strings.TrimPrefix(value, "X(")
	return strings.TrimSuffix(value, ")")
}

// ─── Config map generation ─────────────────────────────────────────────

type define struct {
	name  string
	value string // raw C value (after joining continuations)
}

func genConfigs(out *os.File, path string) {
	defines := parseDefines(path)
	// Resolve references: build lookup name → raw value.
	table := make(map[string]string, len(defines))
	for _, d := range defines {
		table[d.name] = d.value
	}

	// Group by mode (core, info, mark, code, plan).
	type kv struct{ key, value string }
	groups := make(map[string][]kv)
	modeOrder := []string{"core", "info", "mark", "code", "plan"}

	// Only these Config struct fields are valid.
	validFields := map[string]string{
		"keywords": "Keywords",
		"endpoint": "Endpoint",
		"apikey":   "APIKey",
		"model":    "Model",
		"instruct": "Instruct",
		"timeout":  "Timeout",
		"tokens":   "Tokens",
		"tries":    "Tries",
		"pause":    "Pause",
		"temp":     "Temp",
	}

	for _, d := range defines {
		if !strings.HasPrefix(d.name, "V") {
			continue
		}
		rest := d.name[1:]
		under := strings.Index(rest, "_")
		if under == -1 {
			continue
		}
		mode := strings.ToLower(rest[:under])
		key := strings.ToLower(rest[under+1:])
		// Skip keys that aren't Config struct fields.
		fieldName, ok := validFields[key]
		if !ok {
			continue
		}
		val := resolveRef(table, d.name)
		groups[mode] = append(groups[mode], kv{fieldName, val})
	}

	fmt.Fprintf(out, "\n// configs is pre-built from %s.\n", path)
	fmt.Fprintln(out, "var _configs = map[string]Config{")
	for _, mode := range modeOrder {
		kvs := groups[mode]
		if len(kvs) == 0 {
			continue
		}
		fmt.Fprintf(out, "\t%q: {\n", mode)
		for _, kv := range kvs {
			goVal := toGoValue(kv.key, kv.value)
			fmt.Fprintf(out, "\t\t%s: %s,\n", kv.key, goVal)
		}
		fmt.Fprintln(out, "\t},")
	}
	fmt.Fprintln(out, "}")
}

func parseDefines(path string) []define {
	f, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	var defines []define
	cont := false
	var currentName string
	var currentValue strings.Builder

	flush := func() {
		if currentName != "" {
			val := currentValue.String()
			// Normalize: strip surrounding quotes from string values.
			if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
				val = strings.TrimPrefix(val, "\"")
				val = strings.TrimSuffix(val, "\"")
			}
			defines = append(defines, define{currentName, val})
			currentName = ""
			currentValue.Reset()
		}
	}

	for scanner.Scan() {
		line := scanner.Text()

		if cont {
			trimmed := strings.TrimSpace(line)
			cont = false
			if strings.HasSuffix(trimmed, "\\") {
				trimmed = strings.TrimSuffix(trimmed, "\\")
				cont = true
			}
			piece := strings.TrimSpace(trimmed)
			piece = strings.TrimPrefix(piece, "\"")
			for strings.HasSuffix(piece, "\"") {
				piece = strings.TrimSuffix(piece, "\"")
			}
			piece = strings.TrimSuffix(piece, ";")
			currentValue.WriteString(piece)
			if !cont {
				flush()
			}
			continue
		}

		if !strings.HasPrefix(line, "#define ") {
			continue
		}

		flush()

		rest := strings.TrimPrefix(line, "#define ")
		rest = strings.TrimSpace(rest)
		space := strings.Index(rest, " ")
		if space == -1 {
			continue
		}
		name := rest[:space]
		value := strings.TrimSpace(rest[space:])

		cont = strings.HasSuffix(value, "\\")
		if cont {
			value = strings.TrimSuffix(value, "\\")
		}
		value = strings.TrimSuffix(value, ";")

		if !strings.HasPrefix(name, "V") {
			continue
		}

		currentName = name
		currentValue.Reset()
		currentValue.WriteString(value)

		if !cont {
			flush()
		}
	}

	if cont && currentName != "" {
		defines = append(defines, define{currentName, currentValue.String()})
	}

	if err := scanner.Err(); err != nil {
		panic(err)
	}

	return defines
}

func resolveRef(table map[string]string, name string) string {
	val, ok := table[name]
	if !ok {
		return name
	}
	// If the value is a reference to another define, follow it.
	trimmed := strings.TrimSpace(val)
	if trimmed == name {
		return val
	}
	if _, exists := table[trimmed]; exists && strings.HasPrefix(trimmed, "V") {
		// Resolve recursively, but avoid infinite loops.
		resolved := resolveRef(table, trimmed)
		if resolved == trimmed {
			return val // break cycle
		}
		return resolved
	}
	return val
}

// ─── Value to Go literal conversion ────────────────────────────────────

// toGoValue converts a raw C define value to a Go literal for the given Config key.
func toGoValue(key, value string) string {
	value = strings.TrimSpace(value)

	// NULL
	if strings.EqualFold(value, "NULL") {
		switch key {
		case "Keywords":
			return "nil"
		case "Temp":
			return "0.0"
		case "Endpoint", "APIKey", "Model", "Instruct":
			return `""`
		default:
			return "0"
		}
	}

	// Check if this was originally a quoted string (single-line define).
	// Multi-line continuations are already unquoted by parseDefines.
	if strings.HasPrefix(value, "\"") {
		val := value
		val = strings.TrimPrefix(val, "\"")
		for strings.HasSuffix(val, "\"") || strings.HasSuffix(val, ";") {
			val = strings.TrimSuffix(val, "\"")
			val = strings.TrimSuffix(val, ";")
		}
		val = interpretCEscapes(val)
		return fmt.Sprintf("%q", val)
	}

	// Array: ((const char*[]){"a","b", NULL})
	if strings.Contains(value, "(const char*[])") || strings.HasPrefix(value, "{") {
		vals := parseArrayList(value)
		if len(vals) == 0 {
			return "nil"
		}
		var sb strings.Builder
		sb.WriteString("[]string{")
		for i, v := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", v))
		}
		sb.WriteString("}")
		return sb.String()
	}

	// Numeric (int or float)
	if isNumeric(value) {
		return value
	}

	// Must be a string value (from multi-line continuation, already unquoted).
	// Interpret C escape sequences then let %q do the Go escaping.
	val := interpretCEscapes(value)
	return fmt.Sprintf("%q", val)
}

func parseArrayList(value string) []string {
	// Strip C type cast e.g. ((const char*[])
	value = strings.TrimSpace(value)
	idx := strings.Index(value, "{")
	if idx < 0 {
		return nil
	}
	value = value[idx:]

	// Strip braces
	value = strings.TrimPrefix(value, "{")
	value = strings.TrimSuffix(value, "}")
	// Also strip any trailing ) or ;
	for strings.HasSuffix(value, ")") || strings.HasSuffix(value, "}") || strings.HasSuffix(value, ";") {
		value = strings.TrimSuffix(value, ")")
		value = strings.TrimSuffix(value, "}")
		value = strings.TrimSuffix(value, ";")
	}

	parts := strings.Split(value, ",")
	var out []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		p = strings.Trim(p, "\"")
		p = strings.TrimSpace(p)
		if p == "" || strings.EqualFold(p, "NULL") {
			continue
		}
		out = append(out, p)
	}
	return out
}

func isNumeric(value string) bool {
	if value == "" {
		return false
	}
	// Check if it's a valid Go number literal (int or float).
	// Simple check: all digits, possibly with a dot or leading minus.
	hasDot := false
	for i, c := range value {
		if c == '-' && i == 0 {
			continue
		}
		if c == '.' {
			if hasDot {
				return false
			}
			hasDot = true
			continue
		}
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// ─── Constants generation (unchanged) ──────────────────────────────────

// genConstants reads configure.x and generates Go const declarations for
// #define macros that start with V and have quoted string values.
// Multi-line continuations (backslash) are joined, handling C string literal
// concatenation (adjacent "..." "..." strings are merged).
func genConstants(out *os.File, path string) {
	f, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	var defines []struct{ name, value string }
	var currentName string
	var currentValue strings.Builder
	cont := false
	inDefine := false

	for scanner.Scan() {
		line := scanner.Text()

		if cont {
			trimmed := strings.TrimSpace(line)
			cont = false
			if strings.HasSuffix(trimmed, "\\") {
				trimmed = strings.TrimSuffix(trimmed, "\\")
				cont = true
			}
			piece := strings.TrimSpace(trimmed)
			piece = strings.TrimPrefix(piece, "\"")
			for strings.HasSuffix(piece, "\"") {
				piece = strings.TrimSuffix(piece, "\"")
			}
			piece = strings.TrimSuffix(piece, ";")
			currentValue.WriteString(piece)
			if !cont {
				defines = append(defines, struct{ name, value string }{currentName, currentValue.String()})
				inDefine = false
			}
			continue
		}

		if !strings.HasPrefix(line, "#define ") {
			continue
		}

		if inDefine {
			defines = append(defines, struct{ name, value string }{currentName, currentValue.String()})
			inDefine = false
		}

		rest := strings.TrimPrefix(line, "#define ")
		rest = strings.TrimSpace(rest)
		space := strings.Index(rest, " ")
		if space == -1 {
			continue
		}
		name := rest[:space]
		value := strings.TrimSpace(rest[space:])

		if !strings.HasPrefix(name, "V") {
			continue
		}

		cont = strings.HasSuffix(value, "\\")
		if cont {
			value = strings.TrimSuffix(value, "\\")
		}

		value = strings.TrimSuffix(value, ";")

		if !strings.HasPrefix(value, "\"") && !cont {
			continue
		}

		if cont && !strings.HasPrefix(value, "\"") {
			inDefine = true
			currentName = name
			currentValue.Reset()
			continue
		}

		value = strings.TrimPrefix(value, "\"")
		for strings.HasSuffix(value, "\"") {
			value = strings.TrimSuffix(value, "\"")
		}
		value = strings.TrimSuffix(value, ";")

		currentName = name
		currentValue.Reset()
		currentValue.WriteString(value)
		inDefine = true

		if !cont {
			defines = append(defines, struct{ name, value string }{name, currentValue.String()})
			inDefine = false
		}
	}

	if inDefine {
		defines = append(defines, struct{ name, value string }{currentName, currentValue.String()})
	}

	if err := scanner.Err(); err != nil {
		panic(err)
	}

	if len(defines) == 0 {
		return
	}

	fmt.Fprintf(out, "// Auto-generated constants from x/configure.x.\n")
	fmt.Fprintf(out, "const (\n")
	for _, d := range defines {
		val := interpretCEscapes(d.value)
		escaped := strings.ReplaceAll(val, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		escaped = strings.ReplaceAll(escaped, "\n", "\\n")
		escaped = strings.ReplaceAll(escaped, "\r", "\\r")
		escaped = strings.ReplaceAll(escaped, "\t", "\\t")
		fmt.Fprintf(out, "\t%s = \"%s\"\n", d.name, escaped)
	}
	fmt.Fprintf(out, ")\n")
}

// interpretCEscapes replaces C escape sequences in s with their actual characters.
func interpretCEscapes(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			switch s[i+1] {
			case 'n':
				b.WriteByte('\n')
				i++
			case 't':
				b.WriteByte('\t')
				i++
			case 'r':
				b.WriteByte('\r')
				i++
			case '\\':
				b.WriteByte('\\')
				i++
			case '"':
				b.WriteByte('"')
				i++
			case '`':
				b.WriteByte('`')
				i++
			default:
				b.WriteByte(s[i])
			}
		} else {
			b.WriteByte(s[i])
		}
	}
	return b.String()
}