// (c) 2026 FRINKnet & Friends - MIT Licence
//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func main() {
	if err := validateFile("../x/filetypes.x", 3); err != nil {
		panic(err)
	}
	if err := validateFile("../x/prompts.x", 4); err != nil {
		panic(err)
	}

	out, err := os.Create("x_config.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen.go; DO NOT EDIT.")
	fmt.Fprintln(out, "package libvariance")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "import (")
	fmt.Fprintln(out, "\t\"bufio\"")
	fmt.Fprintln(out, "\t\"fmt\"")
	fmt.Fprintln(out, "\t\"os\"")
	fmt.Fprintln(out, "\t\"strings\"")
	fmt.Fprintln(out, ")")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func loadXConfig() ([]FileType, map[string]Config, error) {")
	fmt.Fprintln(out, "\tvar fileTypes []FileType")
	fmt.Fprintln(out, "\tvar configs map[string]Config")
	fmt.Fprintln(out, "\tif err := loadFiletypes(&fileTypes, \"../x/filetypes.x\"); err != nil {")
	fmt.Fprintln(out, "\t\treturn nil, nil, err")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\tif err := loadPrompts(&configs, \"../x/prompts.x\"); err != nil {")
	fmt.Fprintln(out, "\t\treturn nil, nil, err")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn fileTypes, configs, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func loadFiletypes(out *[]FileType, path string) error {")
	fmt.Fprintln(out, "\tfile, err := os.Open(path)")
	fmt.Fprintln(out, "\tif err != nil { return err }")
	fmt.Fprintln(out, "\tdefer file.Close()")
	fmt.Fprintln(out, "\tscanner := bufio.NewScanner(file)")
	fmt.Fprintln(out, "\tlineNo := 0")
	fmt.Fprintln(out, "\tfor scanner.Scan() {")
	fmt.Fprintln(out, "\t\tlineNo++")
	fmt.Fprintln(out, "\t\tline := strings.TrimSpace(scanner.Text())")
	fmt.Fprintln(out, "\t\tif line == \"\" || strings.HasPrefix(line, \"//\") { continue }")
	fmt.Fprintln(out, "\t\targs := splitXArgs(line)")
	fmt.Fprintln(out, "\t\tif len(args) != 3 { return fmt.Errorf(\"%s:%d: expected X(lang, exts, mark), got %q\", path, lineNo, line) }")
	fmt.Fprintln(out, "\t\tft := FileType{Lang: cleanXName(args[0]), Ext: args[1], Mark: trimXValue(args[2])}")
	fmt.Fprintln(out, "\t\tif ft.Lang == \"\" || ft.Ext == \"\" || ft.Mark == \"\" { return fmt.Errorf(\"%s:%d: empty X fields\", path, lineNo) }")
	fmt.Fprintln(out, "\t\t*out = append(*out, ft)")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn scanner.Err()")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func loadPrompts(out *map[string]Config, path string) error {")
	fmt.Fprintln(out, "\tfile, err := os.Open(path)")
	fmt.Fprintln(out, "\tif err != nil { return err }")
	fmt.Fprintln(out, "\tdefer file.Close()")
	fmt.Fprintln(out, "\tscanner := bufio.NewScanner(file)")
	fmt.Fprintln(out, "\tif *out == nil {")
	fmt.Fprintln(out, "\t\t*out = map[string]Config{}")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\tlineNo := 0")
	fmt.Fprintln(out, "\tfor scanner.Scan() {")
	fmt.Fprintln(out, "\t\tlineNo++")
	fmt.Fprintln(out, "\t\tline := strings.TrimSpace(scanner.Text())")
	fmt.Fprintln(out, "\t\tif line == \"\" || strings.HasPrefix(line, \"//\") { continue }")
	fmt.Fprintln(out, "\t\targs := splitXArgs(line)")
	fmt.Fprintln(out, "\t\tif len(args) != 4 { return fmt.Errorf(\"%s:%d: expected X(mode, name, ctype, value), got %q\", path, lineNo, line) }")
	fmt.Fprintln(out, "\t\tmode := cleanXName(args[0])")
	fmt.Fprintln(out, "\t\tname := strings.TrimSpace(args[1])")
	fmt.Fprintln(out, "\t\tctype := strings.TrimSpace(args[2])")
	fmt.Fprintln(out, "\t\tvalue := trimXValue(args[3])")
	fmt.Fprintln(out, "\t\tcfg := (*out)[mode]")
	fmt.Fprintln(out, "\t\tswitch {")
	fmt.Fprintln(out, "\t\tcase name == \"keywords\" && ctype == \"const char**\": cfg.Keywords = splitList(value)")
	fmt.Fprintln(out, "\t\tcase ctype == \"const char*\":")
	fmt.Fprintln(out, "\t\t\tswitch name {")
	fmt.Fprintln(out, "\t\t\tcase \"apiurl\": cfg.APIURL = value")
	fmt.Fprintln(out, "\t\t\tcase \"apikey\": cfg.APIKey = value")
	fmt.Fprintln(out, "\t\t\tcase \"model\": cfg.Model = value")
	fmt.Fprintln(out, "\t\t\tcase \"instruct\": cfg.Instruct = value")
	fmt.Fprintln(out, "\t\t\t}")
	fmt.Fprintln(out, "\t\tcase ctype == \"int\":")
	fmt.Fprintln(out, "\t\t\tswitch name {")
	fmt.Fprintln(out, "\t\t\tcase \"timeout\": cfg.Timeout = atoi(value)")
	fmt.Fprintln(out, "\t\t\tcase \"tokens\": cfg.Tokens = atoi(value)")
	fmt.Fprintln(out, "\t\t\tcase \"tries\": cfg.Tries = atoi(value)")
	fmt.Fprintln(out, "\t\t\tcase \"pause\": cfg.Pause = atoi(value)")
	fmt.Fprintln(out, "\t\t\t}")
	fmt.Fprintln(out, "\t\tcase ctype == \"double\": if name == \"temp\" { cfg.Temp = atof(value) }")
	fmt.Fprintln(out, "\t\t}")
	fmt.Fprintln(out, "\t\t(*out)[mode] = cfg")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn scanner.Err()")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func splitXArgs(line string) []string {")
	fmt.Fprintln(out, "\tline = strings.TrimSpace(line)")
	fmt.Fprintln(out, "\tline = strings.TrimPrefix(line, \"X(\")")
	fmt.Fprintln(out, "\tline = strings.TrimSuffix(line, \")\")")
	fmt.Fprintln(out, "\tvar out []string")
	fmt.Fprintln(out, "\tvar b strings.Builder")
	fmt.Fprintln(out, "\tinQuotes := false")
	fmt.Fprintln(out, "\tinBraces := false")
	fmt.Fprintln(out, "\tfor _, r := range line {")
	fmt.Fprintln(out, "\t\tswitch r {")
	fmt.Fprintln(out, "\t\tcase '\"': inQuotes = !inQuotes; b.WriteRune(r)")
	fmt.Fprintln(out, "\t\tcase '{': if !inQuotes { inBraces = true }; b.WriteRune(r)")
	fmt.Fprintln(out, "\t\tcase '}': if !inQuotes { inBraces = false }; b.WriteRune(r)")
	fmt.Fprintln(out, "\t\tcase ',': if !inQuotes && !inBraces { out = append(out, strings.TrimSpace(b.String())); b.Reset(); continue }; b.WriteRune(r)")
	fmt.Fprintln(out, "\t\tdefault: b.WriteRune(r)")
	fmt.Fprintln(out, "\t\t}")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\tout = append(out, strings.TrimSpace(b.String()))")
	fmt.Fprintln(out, "\treturn out")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func trimXValue(value string) string {")
	fmt.Fprintln(out, "\tvalue = strings.TrimSpace(value)")
	fmt.Fprintln(out, "\tvalue = strings.TrimSuffix(value, \")\")")
	fmt.Fprintln(out, "\tvalue = strings.Trim(value, \"\\\"\")")
	fmt.Fprintln(out, "\treturn strings.TrimSpace(value)")
	fmt.Fprintln(out, "}")
}

func validateFile(path string, expected int) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		args := splitXArgs(line)
		if len(args) != expected {
			return fmt.Errorf("%s:%d: expected %d fields, got %d: %q", path, lineNo, expected, len(args), line)
		}
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	return nil
}

func splitXArgs(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "X(")
	line = strings.TrimSuffix(line, ")")

	var out []string
	var b strings.Builder
	inQuotes := false
	inBraces := false
	for _, r := range line {
		switch r {
		case '"':
			inQuotes = !inQuotes
			b.WriteRune(r)
		case '{':
			if !inQuotes {
				inBraces = true
			}
			b.WriteRune(r)
		case '}':
			if !inQuotes {
				inBraces = false
			}
			b.WriteRune(r)
		case ',':
			if !inQuotes && !inBraces {
				out = append(out, strings.TrimSpace(b.String()))
				b.Reset()
				continue
			}
			b.WriteRune(r)
		default:
			b.WriteRune(r)
		}
	}
	out = append(out, strings.TrimSpace(b.String()))
	return out
}

func cleanXName(value string) string {
	value = strings.TrimSpace(value)
	value = strings.TrimPrefix(value, "X(")
	value = strings.TrimSuffix(value, ")")
	return value
}
