// Code generated by gen.go; DO NOT EDIT.
package libvariance

// Auto-generated constants from x/configure.x.
const (
	VCORE_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"
	VCORE_MODEL = "openrouter/free"
	VCORE_INSTRUCT = "You are a {{language}} Software Architect focused on finding the most concise way to build {{goals}}"
	VFILENAME_INFO = ".v-info"
	VFILENAME_PLAN = ".v-plan"
	VFILE_NOTICE_DEAD = "Out of memory."
	VFILE_NOTICE_GONE = "Cannot find `%s'"
	VFILE_NOTICE_OPEN = "Cannot read `%s'"
	VFILE_NOTICE_READ = "Reading `%s`..."
	VFILE_NOTICE_EDIT = "Updating `%s`..."
	VFILE_NOTICE_VIEW = "Reviewing `%s`...\n - %s"
	VFILE_NOTICE_NOTE = "Thinking about `%s`...\n - %s"
	VFILE_NOTICE_MARK = "Added %d new comments."
	VFILE_NOTICE_GOAL = "No files found for: %s"
	VFILE_NOTICE_DONE = "No comments found in `%s`"
	VTODO_SEARCH_PREAMBLE = "I found these problems:"
	VTODO_SEARCH_CONTINUE = "Want me to fix them?"
	VINFO_INSTRUCT = "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})"
	VINFO_MICROFORMAT = "Respond with these lines and I'll help you:\n\n- `review|path|query`    Inspect source from a file\n- `digest|path|notes`    Write a digest of the file\n- `search|path|words`    Locate words in the codepath\n- `memory|topic|thought` Save a memory for future you\n- `forget|topic|thought` Remove a memory for future you\n- `genius|topic|query`   Get genius advice on hard topics\n- `answer|subject|ideas` Explain your thought to the user\n\nLines MUST be this format or I'll discard them..."
	VINFO_LABEL_CONTEXT = "Project Files"
	VINFO_LABEL_LOCATE = "LOCATE"
	VINFO_LABEL_REVIEW = "REVIEW"
	VINFO_LABEL_SUMMARY = "SUMMARY"
	VINFO_LABEL_MEMORIES = "REMEMBER"
	VINFO_LABEL_EDITED = "Updated code in these files..."
	VINFO_SEARCH_NODATA = "(No matches found)"
	VINFO_SEARCH_PREAMBLE = "Okay I see the files. But you want me to focus on:"
	VINFO_SEARCH_DIRECTIVE = "Yes. What files do you need to answer this:"
	VINFO_SEARCH_ACCEPTED = "Okay, so I need to search terms and review the code to figure this out."
	VINFO_SEARCH_FORMAT = "Respond with `review|path|notes` or `search|path|terms`"
	VINFO_REVIEW_REQUEST = "Okay. Show me the contents of these files..."
	VINFO_REVIEW_ACCEPTED = "Okay, so I need to review files first to figure out how to summarize."
	VINFO_REVIEW_DIRECTIVE = "Please write a digest of this file in your response."
	VINFO_REVIEW_CONTINUE = "Okay that helps. Is it enough info to answer? Let me think about it a bit more."
	VINFO_GENIUS_NODATA = "I'll get back to you with an answer later on..."
	VMARK_INSTRUCT = "You are a {{language}} coding coach adding only {{keyword}} comments for junior developers to fix."
	VMARK_MICROFORMAT = "Return ONLY strict insert points like: `filename|line|TYPE|comment` (of these types: {{keywords}})"
	VMARK_SEARCH_REQUEST = "Okay. I see the source code. But what are your goals?"
	VMARK_SEARCH_PREAMBLE = "Okay, so you want:"
	VMARK_SEARCH_ACCEPTED = "And I need to write comments to instruct you..."
	VMARK_SEARCH_CONTINUE = "If that is my only goal which files do I need to modify?"
	VCODE_INSTRUCT = "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})"
	VCODE_MICROFORMAT = "Respond with as many of these lines as you can:\n\n- `review|path|query`    Inspect source from a file\n- `digest|path|notes`    Write a digest of the file\n- `search|path|words`    Locate words in the codepath\n- `memory|topic|thought` Save a memory for future you\n- `forget|topic|thought` Remove a memory for future you\n- `genius|topic|query`   Get genius advice on hard topics\n- `answer|files|notes` - Explain your plan and changes\n\nBe generous as we get to you goals..."
	VCODE_SOURCE_PREAMBLE = "REMEMBER THESE FILES!!!"
	VCODE_SOURCE_DIRECTIVE = "Include each one corrected in your output..."
	VCODE_SOURCE_ACCEPTED = "Okay. I found these comments:"
	VCODE_SOURCE_CONTINUE = "Are we ready to address the comments?"
	VCODE_SEARCH_PREAMBLE = "Okay I see the files. But you want me to focus on:"
	VCODE_SEARCH_DIRECTIVE = "Search the codebase to answer:"
	VCODE_SEARCH_ACCEPTED = "Okay, so I need to search code first to figure this out. Let me think about what make the most sense."
	VCODE_SEARCH_FORMAT = "Then list the files as `answer|filename|comment` after you do you research."
	VPLAN_INSTRUCT = "You are a {{language}} Software Architect in a planning session. Look and decide how to best implement a step-by-step plan for: {{goal}}"
	VPLAN_MICROFORMAT = "Respond with a complete plan in this exact format:\n\nSUMMARY HEADING\n---\noverall approach, reasons, and guidance\n\n- [ ] specifics of first task with reason\n  - `path/file1`\n  - `path/file2`\n\n- [ ] specifics of another task with reason\n  - `path/file3`\n\nFurther technicall notes and consideration\n\nThe plan must include:\n- A clear summary heading\n- Details explaining the approach\n- At least one task with file references\n- Each task must have a checkbox and reason"
	VPLAN_SEARCH_PREAMBLE = "Okay, you want me to plan a more robust solution for:"
	VPLAN_SEARCH_DIRECTIVE = "Use search and review to understand:"
	VPLAN_SEARCH_ACCEPTED = "Okay, so I need to dig in deep to understand your goal. I need to read a lot of files."
	VPLAN_SEARCH_FORMAT = "Then list plan on answers with files as `answer|file,names|comment`. But first do a lot  of `search` and `review` and ask `genius`."
	VPLAN_SEARCH_CONTINUE = "I think I'm ready to articulate the plan to you if you want."
	VPLAN_SOURCE_PREAMBLE = "STUDY THESE FILES!!!"
	VPLAN_SOURCE_DIRECTIVE = "They may explain the missing pieces..."
	VPLAN_REVIEW_DIRECTIVE = "Review this plan and list what is left."
	VPLAN_REVIEW_DELETION = "We are deleting this plan give me a report."
	VTASK_NOTICE_NONE = "Not yet implemented..."
	VTASK_NOTICE_INFO = "Seaching files...\n - %s\n"
	VTASK_NOTICE_MARK = "Preparing code...\n - %s\n"
	VTASK_NOTICE_CODE = "Coding solution...\n - %s\n"
	VTASK_NOTICE_PLAN = "Preparing a plan...\n - %s\n"
	VTASK_NOTICE_TODO = "Adding notes...\n - %s\n"
	VTASK_NOTICE_NEXT = "Continuing plan...\n - %s\n"
	VTASK_NOTICE_TEST = "Testing solution...\n - %s\n"
	VTASK_NOTICE_EDIT = "Opening editor...\n - %s\n"
)

// fileTypes is pre-built from ../x/filetypes.x.
var _fileTypes = []FileType{
	{ Lang: "c", Ext: ".c .h .x", Mark: "//" },
	{ Lang: "cpp", Ext: ".cpp .hpp .cc", Mark: "/* */" },
	{ Lang: "csharp", Ext: ".cs", Mark: "//" },
	{ Lang: "css", Ext: ".css", Mark: "/* */" },
	{ Lang: "less", Ext: ".less", Mark: "/* */" },
	{ Lang: "sass", Ext: ".sass .scss", Mark: "//" },
	{ Lang: "html", Ext: ".html .htm", Mark: "<!-- -->" },
	{ Lang: "xml", Ext: ".xml .xslt", Mark: "<!-- -->" },
	{ Lang: "svg", Ext: ".svg", Mark: "<!-- -->" },
	{ Lang: "markdown", Ext: ".md", Mark: "<!-- -->" },
	{ Lang: "bash", Ext: ".sh", Mark: "#" },
	{ Lang: "python", Ext: ".py", Mark: "#" },
	{ Lang: "javascript", Ext: ".js", Mark: "//" },
	{ Lang: "typescript", Ext: ".ts", Mark: "//" },
	{ Lang: "lua", Ext: ".lua", Mark: "--" },
	{ Lang: "mk", Ext: ".mk Makefile", Mark: "#" },
	{ Lang: "php", Ext: ".php", Mark: "//" },
	{ Lang: "ruby", Ext: ".rb", Mark: "#" },
	{ Lang: "rust", Ext: ".rs", Mark: "//" },
	{ Lang: "golang", Ext: ".go", Mark: "//" },
	{ Lang: "faust", Ext: ".dsp .lib", Mark: "#" },
	{ Lang: "sql", Ext: ".sql", Mark: "--" },
	{ Lang: "yaml", Ext: ".yml .yaml", Mark: "#" },
	{ Lang: "toml", Ext: ".tml .toml", Mark: "#" },
	{ Lang: "jsonc", Ext: ".jsonc", Mark: "//" },
	{ Lang: "java", Ext: ".java", Mark: "//" },
	{ Lang: "kotlin", Ext: ".kt", Mark: "//" },
	{ Lang: "swift", Ext: ".swift", Mark: "//" },
	{ Lang: "perl", Ext: ".pl .pm", Mark: "#" },
	{ Lang: "r", Ext: ".r", Mark: "#" },
	{ Lang: "dart", Ext: ".dart", Mark: "//" },
	{ Lang: "zig", Ext: ".zig", Mark: "//" },
	{ Lang: "ocaml", Ext: ".ml", Mark: "(* *)" },
	{ Lang: "scala", Ext: ".scala", Mark: "//" },
	{ Lang: "erlang", Ext: ".erl", Mark: "%" },
	{ Lang: "elixir", Ext: ".ex .exs", Mark: "#" },
	{ Lang: "haskell", Ext: ".hs", Mark: "--" },
	{ Lang: "lisp", Ext: ".lisp .cl .lsp .l", Mark: ";" },
	{ Lang: "awk", Ext: ".awk", Mark: "#" },
	{ Lang: "sed", Ext: ".sed", Mark: "#" },
	{ Lang: "ini", Ext: ".ini", Mark: ";" },
	{ Lang: "config", Ext: ".conf .cfg", Mark: "#" },
	{ Lang: "assembly", Ext: ".asm .s", Mark: ";" },
	{ Lang: "pascal", Ext: ".pas", Mark: "{" },
	{ Lang: "fortran", Ext: ".f .f90", Mark: "!" },
	{ Lang: "vim", Ext: ".vim", Mark: "\\" },
	{ Lang: "latex", Ext: ".tex", Mark: "%" },
	{ Lang: "batch", Ext: ".bat .cmd", Mark: "REM" },
	{ Lang: "desktop", Ext: ".desktop", Mark: "#" },
	{ Lang: "gradle", Ext: ".gradle", Mark: "//" },
	{ Lang: "nim", Ext: ".nim", Mark: "#" },
	{ Lang: "julia", Ext: ".jl", Mark: "#" },
	{ Lang: "clojure", Ext: ".clj .cljc .cljs .cljr", Mark: ";" },
	{ Lang: "scheme", Ext: ".scm", Mark: ";" },
	{ Lang: "fsharp", Ext: ".fs .fsx", Mark: "//" },
	{ Lang: "objectivec", Ext: ".m .mm", Mark: "//" },
	{ Lang: "verilog", Ext: ".v", Mark: "//" },
	{ Lang: "vhdl", Ext: ".vhd", Mark: "--" },
	{ Lang: "matlab", Ext: ".m", Mark: "%" },
	{ Lang: "cobol", Ext: ".cbl", Mark: "*>" },
	{ Lang: "prolog", Ext: ".pl .pro", Mark: "%" },
	{ Lang: "smalltalk", Ext: ".st", Mark: "\\" },
	{ Lang: "tcl", Ext: ".tcl", Mark: "#" },
	{ Lang: "powershell", Ext: ".ps1 .psm1 .psd1", Mark: "#" },
	{ Lang: "docker", Ext: "Dockerfile", Mark: "#" },
	{ Lang: "properties", Ext: ".properties", Mark: "#" },
	{ Lang: "nix", Ext: ".nix", Mark: "#" },
	{ Lang: "racket", Ext: ".rkt", Mark: ";" },
	{ Lang: "texinfo", Ext: ".texi", Mark: "@c" },
	{ Lang: "ada", Ext: ".adb .ads", Mark: "--" },
	{ Lang: "rexx", Ext: ".rexx", Mark: "--" },
	{ Lang: "groovy", Ext: ".groovy", Mark: "//" },
	{ Lang: "vlang", Ext: ".v", Mark: "//" },
	{ Lang: "solidity", Ext: ".sol", Mark: "//" },
	{ Lang: "sml", Ext: ".sml", Mark: "(* *)" },
	{ Lang: "rst", Ext: ".rst", Mark: ".." },
	{ Lang: "ninja", Ext: ".ninja", Mark: "#" },
	{ Lang: "cue", Ext: ".cue", Mark: "//" },
	{ Lang: "wat", Ext: ".wat", Mark: ";;" },
	{ Lang: "zigzag", Ext: ".zz", Mark: "--" },
	{ Lang: "csound", Ext: ".csd", Mark: "/* */" },
	{ Lang: "supercollider", Ext: ".sc", Mark: "//" },
	{ Lang: "purescript", Ext: ".purs", Mark: "--" },
	{ Lang: "idris", Ext: ".idr", Mark: "--" },
	{ Lang: "lean", Ext: ".lean", Mark: "--" },
	{ Lang: "graphql", Ext: ".graphql .gql", Mark: "#" },
	{ Lang: "arduino", Ext: ".ino .pde", Mark: "//" },
	{ Lang: "asp", Ext: ".asp .aspx", Mark: "<%-- --%>" },
	{ Lang: "cgi", Ext: ".cgi", Mark: "#" },
	{ Lang: "glsl", Ext: ".glsl .frag .vert .geom", Mark: "//" },
	{ Lang: "wgsl", Ext: ".wgsl", Mark: "#" },
	{ Lang: "cmake", Ext: "CMakeLists.txt .cmake", Mark: "#" },
}

// configs is pre-built from ../x/configure.x.
var _configs = map[string]Config{
	"core": {
		Keywords: []string{"TODO", "FIXME", "BUG", "HACK"},
		Endpoint: "https://openrouter.ai/api/v1/chat/completions",
		APIKey: "",
		Model: "openrouter/free",
		Instruct: "You are a {{language}} Software Architect focused on finding the most concise way to build {{goals}}",
		Timeout: 9000,
		Tokens: 9000,
		Tries: 10,
		Pause: 3,
		Temp: 0.1,
	},
	"info": {
		Keywords: []string{"TODO", "FIXME", "BUG", "HACK"},
		Endpoint: "https://openrouter.ai/api/v1/chat/completions",
		APIKey: "",
		Model: "openrouter/free",
		Instruct: "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})",
		Timeout: 9000,
		Tokens: 1000,
		Tries: 10,
		Pause: 3,
		Temp: 0.3,
	},
	"mark": {
		Keywords: []string{"TODO", "FIXME", "BUG", "HACK"},
		Endpoint: "https://openrouter.ai/api/v1/chat/completions",
		APIKey: "",
		Model: "openrouter/free",
		Instruct: "You are a {{language}} coding coach adding only {{keyword}} comments for junior developers to fix.",
		Timeout: 9000,
		Tokens: 9000,
		Tries: 10,
		Pause: 3,
		Temp: 0.3,
	},
	"code": {
		Keywords: []string{"TODO", "FIXME", "BUG", "HACK"},
		Endpoint: "https://openrouter.ai/api/v1/chat/completions",
		APIKey: "",
		Model: "openrouter/free",
		Instruct: "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})",
		Timeout: 9000,
		Tokens: 9000,
		Pause: 3,
		Temp: 0.1,
	},
	"plan": {
		Keywords: []string{"TODO", "FIXME", "BUG", "HACK"},
		Endpoint: "https://openrouter.ai/api/v1/chat/completions",
		APIKey: "",
		Model: "openrouter/free",
		Instruct: "You are a {{language}} Software Architect in a planning session. Look and decide how to best implement a step-by-step plan for: {{goal}}",
		Timeout: 9000,
		Tokens: 1000,
		Pause: 3,
		Temp: 0.4,
	},
}

func loadXConfig() ([]FileType, map[string]Config, error) {
	return _fileTypes, _configs, nil
}
