// Code generated by gen.go; DO NOT EDIT.
package libvariance

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func loadXConfig() ([]FileType, map[string]Config, error) {
	var fileTypes []FileType
	var configs map[string]Config
	if err := loadFiletypes(&fileTypes, "../x/filetypes.x"); err != nil {
		return nil, nil, err
	}
	if err := loadPrompts(&configs, "../x/prompts.x"); err != nil {
		return nil, nil, err
	}
	return fileTypes, configs, nil
}

func loadFiletypes(out *[]FileType, path string) error {
	file, err := os.Open(path)
	if err != nil { return err }
	defer file.Close()
	scanner := bufio.NewScanner(file)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") { continue }
		args := splitXArgs(line)
		if len(args) != 3 { return fmt.Errorf("%s:%d: expected X(lang, exts, mark), got %q", path, lineNo, line) }
		ft := FileType{Lang: cleanXName(args[0]), Ext: args[1], Mark: trimXValue(args[2])}
		if ft.Lang == "" || ft.Ext == "" || ft.Mark == "" { return fmt.Errorf("%s:%d: empty X fields", path, lineNo) }
		*out = append(*out, ft)
	}
	return scanner.Err()
}

func loadPrompts(out *map[string]Config, path string) error {
	file, err := os.Open(path)
	if err != nil { return err }
	defer file.Close()
	scanner := bufio.NewScanner(file)
	if *out == nil {
		*out = map[string]Config{}
	}
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") { continue }
		args := splitXArgs(line)
		if len(args) != 4 { return fmt.Errorf("%s:%d: expected X(mode, name, ctype, value), got %q", path, lineNo, line) }
		mode := cleanXName(args[0])
		name := strings.TrimSpace(args[1])
		ctype := strings.TrimSpace(args[2])
		value := trimXValue(args[3])
		cfg := (*out)[mode]
		switch {
		case name == "keywords" && ctype == "const char**": cfg.Keywords = splitList(value)
		case ctype == "const char*":
			switch name {
			case "apiurl": cfg.APIURL = value
			case "apikey": cfg.APIKey = value
			case "model": cfg.Model = value
			case "instruct": cfg.Instruct = value
			}
		case ctype == "int":
			switch name {
			case "timeout": cfg.Timeout = atoi(value)
			case "tokens": cfg.Tokens = atoi(value)
			case "tries": cfg.Tries = atoi(value)
			case "pause": cfg.Pause = atoi(value)
			}
		case ctype == "double": if name == "temp" { cfg.Temp = atof(value) }
		}
		(*out)[mode] = cfg
	}
	return scanner.Err()
}

func splitXArgs(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "X(")
	line = strings.TrimSuffix(line, ")")
	var out []string
	var b strings.Builder
	inQuotes := false
	inBraces := false
	for _, r := range line {
		switch r {
		case '"': inQuotes = !inQuotes; b.WriteRune(r)
		case '{': if !inQuotes { inBraces = true }; b.WriteRune(r)
		case '}': if !inQuotes { inBraces = false }; b.WriteRune(r)
		case ',': if !inQuotes && !inBraces { out = append(out, strings.TrimSpace(b.String())); b.Reset(); continue }; b.WriteRune(r)
		default: b.WriteRune(r)
		}
	}
	out = append(out, strings.TrimSpace(b.String()))
	return out
}

func trimXValue(value string) string {
	value = strings.TrimSpace(value)
	value = strings.TrimSuffix(value, ")")
	value = strings.Trim(value, "\"")
	return strings.TrimSpace(value)
}
