// mode, name, ctype, value
X(core, keywords,  const char**, {"TODO","FIXME","BUG","HACK", NULL})
X(core, apiurl,    const char*,  "https://openrouter.ai/api/v1/chat/completions")
X(core, apikey,    const char*,  NULL)
X(core, model,     const char*,  "openrouter/free")
X(core, instruct,  const char*,  "You are a {{language}} Software Architect focused on finding the most concise way to build {{goals}}")
X(core, timeout,   int,          9000)
X(core, tokens,    int,          9000)
X(core, tries,     int,          10)
X(core, pause,     int,          3)
X(core, temp,      double,       0.1)

X(info, keywords,  const char**, NULL)
X(info, apiurl,    const char*,  NULL)
X(info, apikey,    const char*,  NULL)
X(info, model,     const char*,  NULL)
X(info, instruct,  const char*,  "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})")
X(info, timeout,   int,          0)
X(info, tokens,    int,          0)
X(info, tries,     int,          0)
X(info, pause,     int,          0)
X(info, temp,      double,       0.0)

X(mark, keywords,  const char**, NULL)
X(mark, apiurl,    const char*,  NULL)
X(mark, apikey,    const char*,  NULL)
X(mark, model,     const char*,  NULL)
X(mark, instruct,  const char*,  "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})")
X(mark, timeout,   int,          0)
X(mark, tokens,    int,          0)
X(mark, tries,     int,          0)
X(mark, pause,     int,          0)
X(mark, temp,      double,       0.0)

X(code, keywords,  const char**, NULL)
X(code, apiurl,    const char*,  NULL)
X(code, apikey,    const char*,  NULL)
X(code, model,     const char*,  NULL)
X(code, instruct,  const char*,  "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})")
X(code, timeout,   int,          0)
X(code, tokens,    int,          0)
X(code, tries,     int,          0)
X(code, pause,     int,          0)
X(code, temp,      double,       0.0)

X(plan, keywords,  const char**, NULL)
X(plan, apiurl,    const char*,  NULL)
X(plan, apikey,    const char*,  NULL)
X(plan, model,     const char*,  NULL)
X(plan, instruct,  const char*,  "You are a {{language}} coding agent focused ONLY on addressing {{keywords}} comments. Return with FULL fixed file ONLY!!! ({{filename}})")
X(plan, timeout,   int,          0)
X(plan, tokens,    int,          0)
X(plan, tries,     int,          0)
X(plan, pause,     int,          0)
X(plan, temp,      double,       0.0)
